[alias]
cli = "build -p ignix-cli"
loader = "build -p ignix-loader --target x86_64-unknown-uefi"
[target.x86_64-unknown-uefi]
linker = "lld"
# [target.x86_64-unknown-linux-musl]
# rustflags = ["-C", "target-feature=+crt-static"]
